configuration:
  environment: dev
server:
  port: 8000
test:
  variable: "测试下配置中心是否获取到配置"
spring:
  sleuth:
    sampler:
      probability: 1 #全部收集，默认只收集10%
  zipkin:
    base-url: http://127.0.0.1:9411  #zipkin访问地址